my:
  jwt:
    access:
      secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh:
      secret: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/action
    username: mish
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto:update
  main:
    allow-circular-references: true
logging:
level:
root: WARN
org.springframework.security: DEBUG